### ISSUE TITLE
[Feature] Deploy the Project

### ISSUE THREAD

**Issue by dipanshurdev** [Srinivasan-Akash/MAIL_MAN_PRO#1]
Deploy the Project (free), so that everyone can use it easily.

**Comment by Srinivasan-Akash** [comment]
Yes, the product isn't completely built yet & due to exams we are halting the project for 1 week, so probably we might go live on february 1st week. 

Planning for 1 week free trail & a generous paid plan for monthly (100, 190, 200Rs.) & years (1000, 2200, 2400 Rs.)

**Comment by dipanshurdev** [comment]
> Yes, the product isn't completely built yet & due to exams we are halting the project for 1 week, so probably we might go live on february 1st week.
> 
> Planning for 1 week free trail & a generous paid plan for monthly (100, 190, 200Rs.) & years (1000, 2200, 2400 Rs.)

Nice
